services:
  - type: web
    name: ner-landslide-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: landslide_db
      - key: JWT_SECRET_KEY
        sync: false
      - key: TEXTBEE_API_KEY
        sync: false
      - key: TEXTBEE_DEVICE_ID
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DEBUG
        value: "False"
